spring:
  main:
    web-application-type: NONE
    banner-mode: OFF
  datasource:
    hikari:
      connection-init-sql: SET search_path TO ${databaseSchema:public}, public
      data-source-properties:
        rewriteBatchedStatements: true
    url: ${url}
    username: ${username}
    password: ${password}
  batch:
    job:
      enabled: false
  jmx:
    enabled: false
logging:
  level:
    liquibase: ERROR
    io.dsub: INFO
    org:
      reflections: ERROR
      springframework: ERROR
    com.zaxxer.hikari: ERROR
server:
  shutdown: graceful
